### ISSUE TITLE
write after end

### ISSUE THREAD

**Issue by mahnunchik** [rvagg/list-stream#2]
How to pass data down to the stream?

```js
return gulp
  .src('./*.svg')
  .pipe(new ListStream({ objectMode: true, allowHalfOpen: true }, function(err, data) {
    if (err) {
      throw err;
    }

    this.end(new Vinyl({
      path: 'all.svg',
      contents: foobar(data),
    }));
  }))
  .pipe(gulp.dest('./foobar'));
```

Produces the error: 
```bash
NodeError: write after end
    at writeAfterEnd
```

**Comment by rvagg** [comment]
It's best not to try to use it in duplex mode, either as a collector or a writer. The callback is called once all data has been collected, so when you supply a callback it becomes a terminal for a pipe. When you make it without the callback you end up making a writable stream that you can pipe elsewhere.

So if you want to use it to collect `data` and then do something with it, move your destination to inside the callback. `this.end()` should be replaced with something that sends the data elsewhere, maybe to a new pipe. Think of it as a big buffering sink, you collect all of the incoming data into a single blob, `data`, and then you have to do something with it. The ideal use of stream is to process chunks as they come in, but ListStream is for those cases where you can't do anything until you have all the data. So once you have all the `data`, do something new with it. Your pipeline is broken anyway because it had to end for you to know you had all the data, start a new pipeline, or send it somewhere new.

(I don't know gulp so I'm not really sure how you should handle this but maybe there's a `gulp.something(myNewTransformedBlob)`).

If you absolutely need it to be a pipeline, then just implement your own transform stream in object mode, they're really easy to make custom ones these days. You could use the through2 package, but it's probably just as easy to make one from scratch:

```
source.pipe(new Transform({
  transform(chunk, encoding, callback) {
    // do something with the data
  }
})).pipe(dest)
```

In your case, you'll want to collect each `chunk` (and probably in `objectMode`) and then implement a `flush()` function too and when that gets called you can `this.write()` the final thing you've transformed. The `flush()` is called just as the source stream is ending so that's the time to push your final thing down the pipe.

I hope that helps.
